### ISSUE TITLE
unrecognized arguments: --no-resign

### ISSUE THREAD

**Issue by TobiGr** [wardvl/f-droid-nightly-action#5]
I have a setup in which I need to publish my APK as GitHub release and in an F-Droid nightly repo.
I've got this (shortened) workflow:

``` yaml
[...]

- name: "Build release APK"
  run: ./gradlew assembleRelease --stacktrace -DpackageSuffix=nightly

[...]

- name: "Sign release"
  if: ${{ env.new_commit == 'true' }}
  uses: r0adkll/sign-android-release@v1
  id: sign_app
  with:
    releaseDirectory: app/build/outputs/apk/release
    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
    alias: ${{ secrets.ALIAS }}
    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    keyPassword: ${{ secrets.KEY_PASSWORD }}

[...]

- name: F-Droid nightly builds
  uses: wardvl/f-droid-nightly-action@main
  with:
    debug_keystore: ${{ secrets.DEBUG_KEYSTORE }}
    fdroid_nightly_args: --archive-older 10 --file signed-apk.apk --no-resign

``` 

I get the following error:
```
usage: fdroid nightly [-h] [-v] [-q] [--keystore KEYSTORE] [--show-secret-var]
                      [--keep-private-keys] [--no-deploy] [--file FILE]
                      [--no-checksum] [--archive-older ARCHIVE_OLDER]
fdroid nightly: error: unrecognized arguments: --no-resign
```
This should be possible according to the readme:
> This action uses the docker image of the f-droid server. Some changes were made to make this run on GitHub actions. It also adds an option --no-resign to the fdroid nightly command. This can be useful when you include the signing in your own build process. Eg. for system apps that rely on being signed with the system key.

What am I doing wrong? I do not install fdroidserver via the PPA, the APK file is located in the root dir after switching branches and moving the file,
